---
- name: Create directory for Semaphore data
  file:
    path: /opt/semaphore
    state: directory

- name: Copy environment file for Semaphore
  template:
    src: env.j2
    dest: /opt/semaphore/.env

- name: Create custom network for Semaphore and PostgreSQL
  docker_network:
    name: semaphore_net
    driver: bridge
    state: present

- name: Run PostgreSQL Container
  become: true
  docker_container:
    name: semaphore_postgres
    image: postgres:12
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    state: started
    networks:
      - name: semaphore_net

- name: Wait for PSQL to be ready
  wait_for:
    host: "127.0.0.1"
    port: 5432
    delay: 10
    timeout: 300

- name: Run Semaphore Container
  become: true
  docker_container:
    name: semaphore
    image: semaphoreui/semaphore:latest
    ports:
      - "3000:3000"
    env_file: /opt/semaphore/.env
    links:
      - semaphore_postgres
    state: started
    restart_policy: always
    networks:
      - name: semaphore_net

- name: Get list of users in Semaphore
  shell: |
    docker exec -it semaphore /bin/sh -c "semaphore user list"
  register: user_list
  changed_when: false
  become: true

- name: Check if 'admin' exists
  set_fact:
    user_exists: "{{ 'admin' in user_list.stdout }}"
    
- name: Create user admin in Semaphore
  shell: |
    docker exec -it semaphore /bin/sh -c "semaphore user add --admin --login admin --name emil --email emil@amirakulov.com --password admin"
  become: true
  when: not user_exists
